// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateDailyReport() {
  return window['go']['main']['App']['GenerateDailyReport']();
}

export function GenerateWeeklyReport() {
  return window['go']['main']['App']['GenerateWeeklyReport']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetProviders() {
  return window['go']['main']['App']['GetProviders']();
}

export function GetReportHistory() {
  return window['go']['main']['App']['GetReportHistory']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetTodaySummary() {
  return window['go']['main']['App']['GetTodaySummary']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenReportsDir() {
  return window['go']['main']['App']['OpenReportsDir']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function TestLLMConnection() {
  return window['go']['main']['App']['TestLLMConnection']();
}
