// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {main} from '../models';

export function GenerateDailyReport():Promise<string>;

export function GenerateWeeklyReport():Promise<string>;

export function GetConfig():Promise<config.Config>;

export function GetProviders():Promise<Array<main.ProviderInfo>>;

export function GetReportHistory():Promise<Array<main.ReportInfo>>;

export function GetStatus():Promise<main.Status>;

export function GetTodaySummary():Promise<main.TodaySummary>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenReportsDir():Promise<void>;

export function SaveConfig(arg1:main.SaveConfigRequest):Promise<void>;

export function TestLLMConnection():Promise<string>;
